### ISSUE TITLE
Ribbon SBC 5000 does not work

### ISSUE THREAD

**Issue by fuf42** [consentfactory/pyribbon#1]
Hi,

I just testet with SBC 5000, it does not work, as - perhaps only in my case - the SBC does not use this login URL above:

```
fertig@hornisse:..projects/sbc > python3 ribbonapitest.py
Traceback (most recent call last):
  File "ribbonapitest.py", line 64, in <module>
    sys.exit(main())
  File "ribbonapitest.py", line 45, in main
    session = session_creator()
  File "ribbonapitest.py", line 37, in session_creator
    open_response = session.open()
  File "/home/fertig/projects/sbc/pyribbon.py", line 21, in open
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://192.xxx.xxx.xxx/rest/login
fertig@hornisse:..projects/sbc >
```

When I tested this (month ago), this first code test worked:

```
import requests
import xmltodict
import json
import pprint
import sys
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

sbc = "192.xxx.xxx.xxx"
username = "restapitest"
password = "xxxxxxxxxxxxxxxxxxxx"

url = 'https://%s/api/config/addressContext/' % sbc
headers = {}

try:
  r = requests.get(url, headers=headers, auth=(username, password), verify=False)
  # print r.status_code, r.history
except Exception, why:
  print "error contacting sbc:", why
  sys.exit(1)

responsedict = {}
if r.ok:
  responsedict = dict(xmltodict.parse(r.text))

print(json.dumps(responsedict, indent=4))

```

If you're still working on this code, perhaps I could help you extend this for SBC 5000

Christian

**Comment by commitconfirm** [comment]
Unfortunately I'm no longer developing for Sonus/Ribbon devices anymore, but doing a cursory search at the SBC 5k/7k API docs, a quick change in pyribbon.py could solve the problem for you.

Looks like if you change [line 11 on pyribbon.py](https://github.com/consentfactory/pyribbon/blob/00d25216ad57b9410464415547a4351c5a7c44a7/pyribbon.py#L11) to the SBC 5k/7k API path, that should fix it:

```
self.url = f"https://{host}/rest"
```
Change it to:
```
self.url = f"https://{host}/api"
```

Reference docs:

[SBC 5k/7k REST API Samples](https://support.sonus.net/display/SBXAPIDOC/REST+API+Samples)

[SBC 1k/2k REST API Samples](https://support.sonus.net/display/UXDOC90/REST+Sample+-+Login+Resource)

Let me know if that works.

Seems like it its current state the code doesn't support SBC 5k/7k, so I should update the documentation to indicate that (or change some of the code for it).
